Notebook para juntar csvs com as informações coletadas e estimar dados importantes

In [4]:
import pandas as pd
import re

In [68]:
data_list = []
padrao_avaliadores = 'avaliador\d$'
for i in range(2006, 2025):
    data = pd.read_csv(f"csvs/final_defesas{i}.csv", index_col=0)
    avaliadores = [col for col in data.columns if re.search(padrao_avaliadores, col)]
    data['ano'] = i
    data_list.append(data)

In [69]:
data_final = pd.concat(data_list)

In [70]:
data_final.head()

,tipo,url,orientador,avaliador1,avaliador2,avaliador3,avaliador4,avaliador5,avaliador6,orientador_filiação,...,avaliador5_keyword_1,avaliador5_keyword_2,avaliador5_keyword_3,avaliador5_keyword_4,avaliador3_keyword_8,avaliador3_keyword_9,avaliador3_keyword_10,avaliador3_keyword_11,avaliador3_keyword_12,avaliador3_keyword_13
0,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-6540-8686,sem orcid,orcid.org/0000-0002-8803-0401,NaN,NaN,NaN,NaN,University of Campinas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-6540-8686,sem orcid,orcid.org/0000-0002-7002-875X,NaN,NaN,NaN,NaN,University of Campinas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0003-4869-5190,orcid.org/0000-0002-8803-0401,orcid.org/0000-0003-1574-0362,NaN,NaN,NaN,NaN,Universidade Estadual de Campinas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0001-5685-8004,sem orcid,orcid.org/0000-0002-7002-875X,NaN,NaN,NaN,NaN,no info,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0001-5685-8004,orcid.org/0000-0001-5489-4909,orcid.org/0000-0002-9554-1381,orcid.org/0000-0002-3159-4839,NaN,NaN,NaN,no info,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
print(f"Total de defesas antes de limpeza = {data_final.shape[0]}")

Total de defesas antes de limpeza = 1030

In [72]:
data_final = data_final[(data_final["orientador"] == data_final["orientador"]) & (data_final["orientador"] != "Selenium_error")]

In [73]:
data_final["ano"].value_counts()

ano
2006    71
2020    69
2015    61
2016    61
2010    58
2013    58
2017    57
2021    57
2012    55
2024    55
2022    54
2018    54
2011    52
2019    50
2023    48
2009    47
2014    44
2007    41
2008    36
Name: count, dtype: int64

In [74]:
for ano in data_final["ano"].value_counts(sort=False).index:
    print(f"{ano}:")
    data_final_ano = data_final[data_final["ano"] == ano]
    for curso, qtd in zip(data_final_ano["tipo"].value_counts().index, data_final_ano["tipo"].value_counts().values):
        print(f"    {curso}: {qtd}")

2006:
    MESTRADO: 31
    MESTRADO PROFISSIONAL: 28
    DOUTORADO: 12
2007:
    MESTRADO: 30
    DOUTORADO: 10
    MESTRADO PROFISSIONAL: 1
2008:
    MESTRADO: 25
    DOUTORADO: 11
2009:
    MESTRADO: 32
    DOUTORADO: 15
2010:
    DOUTORADO: 13
2011:
    MESTRADO: 38
    DOUTORADO: 14
2012:
    MESTRADO: 34
    DOUTORADO: 21
2013:
    MESTRADO: 40
    DOUTORADO: 18
2014:
    MESTRADO: 31
    DOUTORADO: 13
2015:
    MESTRADO: 43
    DOUTORADO: 18
2016:
    MESTRADO: 37
    DOUTORADO: 24
2017:
    MESTRADO: 40
    DOUTORADO: 17
2018:
    MESTRADO: 37
    DOUTORADO: 17
2019:
    MESTRADO: 35
    DOUTORADO: 15
2020:
    MESTRADO: 54
    DOUTORADO: 15
2021:
    MESTRADO: 40
    DOUTORADO: 17
2022:
    MESTRADO: 35
    DOUTORADO: 19
2023:
    MESTRADO: 29
    DOUTORADO: 19
2024:
    MESTRADO: 34
    DOUTORADO: 21

## Adicionar informações de gênero

In [39]:
gender_data = pd.read_csv("csvs/genero.csv")

In [40]:
gender_data.head()

                           orcid              nome    genero
0  orcid.org/0000-0002-0503-7297               NaN       NaN
1  orcid.org/0000-0003-3589-1619    Renata Galante  Feminino
2  orcid.org/0000-0001-9068-938X      Sandra Avila  Feminino
3  orcid.org/0000-0002-5243-0921   Fernanda Andaló  Feminino
4  orcid.org/0000-0001-8309-6367  Ariadne Carvalho  Feminino

In [75]:
avaliadores = [col for col in data_final.columns if re.search(padrao_avaliadores, col)]
avaliadores.append("orientador")

In [76]:
avaliadores

['avaliador1',
 'avaliador2',
 'avaliador3',
 'avaliador4',
 'avaliador5',
 'avaliador6',
 'orientador']

In [77]:
for col in avaliadores:
    data_final[f"{col}_genero"] = pd.NA

In [45]:
from collections import defaultdict

In [78]:
generos = defaultdict(list)
for col in avaliadores:
    for orcid, idx in zip(data_final[col].values, data_final[col].index):
        if orcid == "sem orcid": 
            # generos[col].append((orcid, idx, "sem orcid", ""))
            generos[col].append({
                "orcid": orcid, "idx": idx, "gênero": "sem orcid", "nome orcid": 'sem orcid'
            })
            continue
        if gender_data[gender_data["orcid"] == orcid].shape[0] == 0: # não tem gênero ou nome da pessoa anotado para esse orcid
            generos[col].append({
                "orcid": orcid, "idx": idx, "gênero": "não anotado", "nome orcid": 'não anotado'
            })
            continue
        genero = gender_data[gender_data["orcid"] == orcid]["genero"].values[0]
        nome = gender_data[gender_data["orcid"] == orcid]["nome"].values[0]
        generos[col].append({
                "orcid": orcid, "idx": idx, "gênero": genero, "nome orcid": nome
            })

In [79]:
for col, infos in generos.items():
    for info in infos:
        idx = info["idx"]
        genero = info["gênero"]
        data_final.at[idx, f"{col}_genero"] = genero

In [80]:
data_final

,tipo,url,orientador,avaliador1,avaliador2,avaliador3,avaliador4,avaliador5,avaliador6,orientador_filiação,...,avaliador3_keyword_11,avaliador3_keyword_12,avaliador3_keyword_13,avaliador1_genero,avaliador2_genero,avaliador3_genero,avaliador4_genero,avaliador5_genero,avaliador6_genero,orientador_genero
0,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-6540-8686,sem orcid,orcid.org/0000-0002-8803-0401,NaN,NaN,NaN,NaN,University of Campinas,...,NaN,NaN,NaN,sem orcid,Masculino,não anotado,não anotado,não anotado,não anotado,Masculino
1,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-6540-8686,sem orcid,orcid.org/0000-0002-7002-875X,NaN,NaN,NaN,NaN,University of Campinas,...,NaN,NaN,NaN,Masculino,Feminino,não anotado,não anotado,não anotado,não anotado,Feminino
2,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0003-4869-5190,orcid.org/0000-0002-8803-0401,orcid.org/0000-0003-1574-0362,NaN,NaN,NaN,NaN,Universidade Estadual de Campinas,...,NaN,NaN,NaN,sem orcid,Masculino,não anotado,não anotado,não anotado,não anotado,Masculino
3,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0001-5685-8004,sem orcid,orcid.org/0000-0002-7002-875X,NaN,NaN,NaN,NaN,no info,...,NaN,NaN,NaN,Masculino,Feminino,não anotado,não anotado,não anotado,não anotado,Masculino
4,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0001-5685-8004,orcid.org/0000-0001-5489-4909,orcid.org/0000-0002-9554-1381,orcid.org/0000-0002-3159-4839,NaN,NaN,NaN,no info,...,NaN,NaN,NaN,Masculino,Masculino,não anotado,não anotado,não anotado,não anotado,Masculino
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,DOUTORADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-4236-8212,orcid.org/0000-0003-0158-7432,sem orcid,orcid.org/0000-0001-9722-5764,orcid.org/0000-0002-8727-4500,NaN,NaN,Universidade Estadual de Campinas,...,NaN,NaN,NaN,Masculino,sem orcid,Feminino,Masculino,não anotado,não anotado,Masculino
51,DOUTORADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-4236-8212,orcid.org/0000-0003-4929-7258,orcid.org/0000-0003-1574-0362,orcid.org/0000-0002-1534-5744,orcid.org/0000-0002-3754-9115,NaN,NaN,Universidade Estadual de Campinas,...,NaN,NaN,NaN,Feminino,Masculino,Feminino,Masculino,não anotado,não anotado,Masculino
52,DOUTORADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-6731-1482,orcid.org/0000-0002-1310-0997,orcid.org/0000-0001-7048-6585,orcid.org/0000-0001-9241-2229,orcid.org/0000-0001-9577-9309,NaN,NaN,no info,...,NaN,NaN,NaN,Masculino,Masculino,Masculino,Masculino,não anotado,não anotado,Masculino
53,DOUTORADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-9529-4253,orcid.org/0000-0002-2042-4623,orcid.org/0000-0001-9924-0079,orcid.org/0000-0002-1649-6843,orcid.org/0000-0001-7434-2642,NaN,NaN,University of Campinas,...,NaN,NaN,NaN,Masculino,Masculino,Feminino,Masculino,não anotado,não anotado,Masculino
54,DOUTORADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-4830-5298,orcid.org/0009-0000-2453-6617,orcid.org/0000-0002-1736-544X,orcid.org/0000-0002-2431-8457,orcid.org/0000-0001-5804-950X,NaN,NaN,Universidade Estadual de Campinas,...,Death and Technologies,Gender,race and Technology,Feminino,Feminino,Masculino,Masculino,não anotado,não anotado,Feminino

## Salvando dataframe final

In [81]:
data_final.to_csv("final_defesas_2006a2024.csv", index=False)