Notebook para juntar csvs com as informações coletadas e estimar dados importantes

In [1]:
import pandas as pd
import re

In [2]:
data_list = []
padrao_avaliadores = 'avaliador\d$'
for i in range(2006, 2025):
    data = pd.read_csv(f"csvs/final_defesas{i}.csv", index_col=0)
    avaliadores = [col for col in data.columns if re.search(padrao_avaliadores, col)]
    data['ano'] = i
    data_list.append(data)

In [3]:
data_final = pd.concat(data_list)

In [4]:
data_final.head()

,tipo,url,orientador,avaliador1,avaliador2,avaliador3,avaliador4,avaliador5,avaliador6,orientador_filiação,...,avaliador5_keyword_1,avaliador5_keyword_2,avaliador5_keyword_3,avaliador5_keyword_4,avaliador3_keyword_8,avaliador3_keyword_9,avaliador3_keyword_10,avaliador3_keyword_11,avaliador3_keyword_12,avaliador3_keyword_13
0,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-6540-8686,sem orcid,orcid.org/0000-0002-8803-0401,NaN,NaN,NaN,NaN,University of Campinas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-6540-8686,sem orcid,orcid.org/0000-0002-7002-875X,NaN,NaN,NaN,NaN,University of Campinas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0003-4869-5190,orcid.org/0000-0002-8803-0401,orcid.org/0000-0003-1574-0362,NaN,NaN,NaN,NaN,Universidade Estadual de Campinas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0001-5685-8004,sem orcid,orcid.org/0000-0002-7002-875X,NaN,NaN,NaN,NaN,no info,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0001-5685-8004,orcid.org/0000-0001-5489-4909,orcid.org/0000-0002-9554-1381,orcid.org/0000-0002-3159-4839,NaN,NaN,NaN,no info,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(f"Total de defesas antes de limpeza = {data_final.shape[0]}")

Total de defesas antes de limpeza = 1030

In [4]:
data_final = data_final[(data_final["orientador"] == data_final["orientador"]) & (data_final["orientador"] != "Selenium_error")]

In [5]:
data_final["ano"].value_counts()

ano
2006    71
2020    69
2015    61
2016    61
2010    58
2013    58
2017    57
2021    57
2012    55
2024    55
2022    54
2018    54
2011    52
2019    50
2023    48
2009    47
2014    44
2007    41
2008    36
Name: count, dtype: int64

In [8]:
for ano in data_final["ano"].value_counts(sort=False).index:
    print(f"{ano}:")
    data_final_ano = data_final[data_final["ano"] == ano]
    for curso, qtd in zip(data_final_ano["tipo"].value_counts().index, data_final_ano["tipo"].value_counts().values):
        print(f"    {curso}: {qtd}")

2006:
    MESTRADO: 31
    MESTRADO PROFISSIONAL: 28
    DOUTORADO: 12
2007:
    MESTRADO: 30
    DOUTORADO: 10
    MESTRADO PROFISSIONAL: 1
2008:
    MESTRADO: 25
    DOUTORADO: 11
2009:
    MESTRADO: 32
    DOUTORADO: 15
2010:
    DOUTORADO: 13
2011:
    MESTRADO: 38
    DOUTORADO: 14
2012:
    MESTRADO: 34
    DOUTORADO: 21
2013:
    MESTRADO: 40
    DOUTORADO: 18
2014:
    MESTRADO: 31
    DOUTORADO: 13
2015:
    MESTRADO: 43
    DOUTORADO: 18
2016:
    MESTRADO: 37
    DOUTORADO: 24
2017:
    MESTRADO: 40
    DOUTORADO: 17
2018:
    MESTRADO: 37
    DOUTORADO: 17
2019:
    MESTRADO: 35
    DOUTORADO: 15
2020:
    MESTRADO: 54
    DOUTORADO: 15
2021:
    MESTRADO: 40
    DOUTORADO: 17
2022:
    MESTRADO: 35
    DOUTORADO: 19
2023:
    MESTRADO: 29
    DOUTORADO: 19
2024:
    MESTRADO: 34
    DOUTORADO: 21

## Adicionar informações de gênero

In [6]:
gender_data = pd.read_csv("csvs/genero.csv")

In [10]:
gender_data.head()

                           orcid              nome    genero
0  orcid.org/0000-0002-0503-7297               NaN       NaN
1  orcid.org/0000-0003-3589-1619    Renata Galante  Feminino
2  orcid.org/0000-0001-9068-938X      Sandra Avila  Feminino
3  orcid.org/0000-0002-5243-0921   Fernanda Andaló  Feminino
4  orcid.org/0000-0001-8309-6367  Ariadne Carvalho  Feminino

In [7]:
avaliadores = [col for col in data_final.columns if re.search(padrao_avaliadores, col)]
avaliadores.append("orientador")

In [8]:
avaliadores

['avaliador1',
 'avaliador2',
 'avaliador3',
 'avaliador4',
 'avaliador5',
 'avaliador6',
 'orientador']

In [9]:
for col in avaliadores:
    data_final[f"{col}_genero"] = pd.NA

In [10]:
from collections import defaultdict

In [12]:
orcid

'orcid.org/0000-0002-4830-5298'

In [13]:
generos = defaultdict(list)
for col in avaliadores:
    for orcid, idx in zip(data_final[col].values, data_final[col].index):
        if orcid == "sem orcid": 
            # generos[col].append((orcid, idx, "sem orcid", ""))
            generos[col].append({
                "orcid": orcid, "idx": idx, "gênero": "sem orcid", "nome orcid": 'sem orcid'
            })
            continue
        if gender_data[gender_data["orcid"] == orcid].shape[0] == 0: # não tem gênero ou nome da pessoa anotado para esse orcid
            generos[col].append({
                "orcid": orcid, "idx": idx, "gênero": "não anotado", "nome orcid": 'não anotado'
            })
            continue
        genero = gender_data[gender_data["orcid"] == orcid]["genero"].values[0]
        nome = gender_data[gender_data["orcid"] == orcid]["nome"].values[0]
        if orcid.split("/")[-1] == "0000-0002-3823-8941":
            print(nome, genero)
        generos[col].append({
                "orcid": orcid, "idx": idx, "gênero": genero, "nome orcid": nome
            })

Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino
Luiz Eduardo Buzato Masculino

In [14]:
generos["orientador"]

[{'orcid': 'orcid.org/0000-0002-6540-8686',
  'idx': 0,
  'gênero': 'Masculino',
  'nome orcid': 'Paulo de Geus'},
 {'orcid': 'orcid.org/0000-0002-6540-8686',
  'idx': 1,
  'gênero': 'Masculino',
  'nome orcid': 'Paulo de Geus'},
 {'orcid': 'orcid.org/0000-0003-4869-5190',
  'idx': 2,
  'gênero': 'Masculino',
  'nome orcid': 'Guido Araujo'},
 {'orcid': 'orcid.org/0000-0001-5685-8004',
  'idx': 3,
  'gênero': 'Masculino',
  'nome orcid': 'Siome Goldenstein'},
 {'orcid': 'orcid.org/0000-0001-5685-8004',
  'idx': 4,
  'gênero': 'Masculino',
  'nome orcid': 'Siome Goldenstein'},
 {'orcid': 'orcid.org/0000-0002-2914-5380',
  'idx': 5,
  'gênero': 'Masculino',
  'nome orcid': 'Alexandre Falcao'},
 {'orcid': 'orcid.org/0000-0001-5201-1244',
  'idx': 6,
  'gênero': 'Masculino',
  'nome orcid': 'Jacques Wainer'},
 {'orcid': 'orcid.org/0000-0003-2046-602X',
  'idx': 7,
  'gênero': 'Masculino',
  'nome orcid': 'Nelson L. S. da Fonseca'},
 {'orcid': 'sem orcid',
  'idx': 8,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-8856-194X',
  'idx': 9,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Anido'},
 {'orcid': 'orcid.org/0000-0002-1067-6421',
  'idx': 10,
  'gênero': 'Masculino',
  'nome orcid': 'Flávio K. Miyazawa'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 11,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'sem orcid',
  'idx': 12,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0003-2046-602X',
  'idx': 13,
  'gênero': 'Masculino',
  'nome orcid': 'Nelson L. S. da Fonseca'},
 {'orcid': 'orcid.org/0000-0002-6540-8686',
  'idx': 14,
  'gênero': 'Masculino',
  'nome orcid': 'Paulo de Geus'},
 {'orcid': 'orcid.org/0000-0002-4830-5298',
  'idx': 15,
  'gênero': 'Feminino',
  'nome orcid': 'Maria Cecilia Calani Baranauskas'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 16,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0003-4549-7105',
  'idx': 17,
  'gênero': 'Feminino',
  'nome orcid': 'Cecilia Mary Fischer Rubira Rubira'},
 {'orcid': 'sem orcid',
  'idx': 18,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0003-4869-5190',
  'idx': 19,
  'gênero': 'Masculino',
  'nome orcid': 'Guido Araujo'},
 {'orcid': 'orcid.org/0000-0003-4290-6508',
  'idx': 20,
  'gênero': 'Feminino',
  'nome orcid': 'Eliane Martins'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 21,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0002-1067-6421',
  'idx': 22,
  'gênero': 'Masculino',
  'nome orcid': 'Flávio K. Miyazawa'},
 {'orcid': 'orcid.org/0000-0003-2046-602X',
  'idx': 23,
  'gênero': 'Masculino',
  'nome orcid': 'Nelson L. S. da Fonseca'},
 {'orcid': 'orcid.org/0000-0003-3333-6822',
  'idx': 24,
  'gênero': 'Masculino',
  'nome orcid': 'Zanoni Dias'},
 {'orcid': 'orcid.org/0000-0003-3333-6822',
  'idx': 25,
  'gênero': 'Masculino',
  'nome orcid': 'Zanoni Dias'},
 {'orcid': 'orcid.org/0000-0002-8856-194X',
  'idx': 26,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Anido'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 27,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'orcid.org/0000-0002-6023-5982',
  'idx': 28,
  'gênero': 'Feminino',
  'nome orcid': 'Islene Calciolari Garcia'},
 {'orcid': 'sem orcid',
  'idx': 29,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-5945-0845',
  'idx': 30,
  'gênero': 'Masculino',
  'nome orcid': 'Cid de Souza'},
 {'orcid': 'orcid.org/0000-0003-2046-602X',
  'idx': 31,
  'gênero': 'Masculino',
  'nome orcid': 'Nelson L. S. da Fonseca'},
 {'orcid': 'orcid.org/0000-0003-4290-6508',
  'idx': 32,
  'gênero': 'Feminino',
  'nome orcid': 'Eliane Martins'},
 {'orcid': 'orcid.org/0000-0003-4290-6508',
  'idx': 33,
  'gênero': 'Feminino',
  'nome orcid': 'Eliane Martins'},
 {'orcid': 'orcid.org/0000-0003-2046-602X',
  'idx': 34,
  'gênero': 'Masculino',
  'nome orcid': 'Nelson L. S. da Fonseca'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 35,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0002-1914-5790',
  'idx': 36,
  'gênero': 'Masculino',
  'nome orcid': 'Mario Jino'},
 {'orcid': 'orcid.org/0000-0002-4830-5298',
  'idx': 37,
  'gênero': 'Feminino',
  'nome orcid': 'Maria Cecilia Calani Baranauskas'},
 {'orcid': 'orcid.org/0000-0002-4830-5298',
  'idx': 38,
  'gênero': 'Feminino',
  'nome orcid': 'Maria Cecilia Calani Baranauskas'},
 {'orcid': 'sem orcid',
  'idx': 39,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0003-4290-6508',
  'idx': 40,
  'gênero': 'Feminino',
  'nome orcid': 'Eliane Martins'},
 {'orcid': 'sem orcid',
  'idx': 41,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0003-4290-6508',
  'idx': 42,
  'gênero': 'Feminino',
  'nome orcid': 'Eliane Martins'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 43,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0003-4549-7105',
  'idx': 44,
  'gênero': 'Feminino',
  'nome orcid': 'Cecilia Mary Fischer Rubira Rubira'},
 {'orcid': 'sem orcid',
  'idx': 45,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0003-4549-7105',
  'idx': 46,
  'gênero': 'Feminino',
  'nome orcid': 'Cecilia Mary Fischer Rubira Rubira'},
 {'orcid': 'orcid.org/0000-0002-3891-1593',
  'idx': 47,
  'gênero': 'Masculino',
  'nome orcid': 'mario cortes'},
 {'orcid': 'sem orcid',
  'idx': 48,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'sem orcid',
  'idx': 49,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 50,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 51,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0002-1914-5790',
  'idx': 52,
  'gênero': 'Masculino',
  'nome orcid': 'Mario Jino'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 53,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0002-4830-5298',
  'idx': 54,
  'gênero': 'Feminino',
  'nome orcid': 'Maria Cecilia Calani Baranauskas'},
 {'orcid': 'orcid.org/0000-0002-3823-8941',
  'idx': 55,
  'gênero': 'Masculino',
  'nome orcid': 'Luiz Eduardo Buzato'},
 {'orcid': 'sem orcid',
  'idx': 56,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-8803-0401',
  'idx': 57,
  'gênero': 'Masculino',
  'nome orcid': 'Rodolfo Azevedo'},
 {'orcid': 'sem orcid',
  'idx': 58,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'sem orcid',
  'idx': 59,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-6540-8686',
  'idx': 60,
  'gênero': 'Masculino',
  'nome orcid': 'Paulo de Geus'},
 {'orcid': 'orcid.org/0000-0001-5201-1244',
  'idx': 61,
  'gênero': 'Masculino',
  'nome orcid': 'Jacques Wainer'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 62,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'sem orcid',
  'idx': 63,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-4830-5298',
  'idx': 64,
  'gênero': 'Feminino',
  'nome orcid': 'Maria Cecilia Calani Baranauskas'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 65,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0003-4549-7105',
  'idx': 66,
  'gênero': 'Feminino',
  'nome orcid': 'Cecilia Mary Fischer Rubira Rubira'},
 {'orcid': 'orcid.org/0000-0002-1067-6421',
  'idx': 67,
  'gênero': 'Masculino',
  'nome orcid': 'Flávio K. Miyazawa'},
 {'orcid': 'orcid.org/0000-0003-4290-6508',
  'idx': 68,
  'gênero': 'Feminino',
  'nome orcid': 'Eliane Martins'},
 {'orcid': 'sem orcid',
  'idx': 69,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-6023-5982',
  'idx': 70,
  'gênero': 'Feminino',
  'nome orcid': 'Islene Calciolari Garcia'},
 {'orcid': 'orcid.org/0000-0001-7878-4990',
  'idx': 0,
  'gênero': 'Masculino',
  'nome orcid': 'Joao Meidanis'},
 {'orcid': 'orcid.org/0000-0003-4549-7105',
  'idx': 1,
  'gênero': 'Feminino',
  'nome orcid': 'Cecilia Mary Fischer Rubira Rubira'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 2,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0002-2914-5380',
  'idx': 3,
  'gênero': 'Masculino',
  'nome orcid': 'Alexandre Falcao'},
 {'orcid': 'orcid.org/0000-0002-8803-0401',
  'idx': 4,
  'gênero': 'Masculino',
  'nome orcid': 'Rodolfo Azevedo'},
 {'orcid': 'orcid.org/0000-0001-9772-263X',
  'idx': 5,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Torres'},
 {'orcid': 'orcid.org/0000-0003-4549-7105',
  'idx': 6,
  'gênero': 'Feminino',
  'nome orcid': 'Cecilia Mary Fischer Rubira Rubira'},
 {'orcid': 'orcid.org/0000-0002-3159-4839',
  'idx': 7,
  'gênero': 'Masculino',
  'nome orcid': 'Jorge Stolfi'},
 {'orcid': 'sem orcid',
  'idx': 8,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'sem orcid',
  'idx': 9,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'sem orcid',
  'idx': 10,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-6731-1482',
  'idx': 11,
  'gênero': 'Masculino',
  'nome orcid': 'Julio Cesar Lopez Hernandez'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 12,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0002-9539-6874',
  'idx': 13,
  'gênero': 'Masculino',
  'nome orcid': 'Sandro Rigo'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 14,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 15,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'orcid.org/0000-0001-5201-1244',
  'idx': 16,
  'gênero': 'Masculino',
  'nome orcid': 'Jacques Wainer'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 17,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'orcid.org/0000-0001-8923-0432',
  'idx': 18,
  'gênero': 'Masculino',
  'nome orcid': 'Tomasz Kowaltowski'},
 {'orcid': 'orcid.org/0000-0001-9772-263X',
  'idx': 19,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Torres'},
 {'orcid': 'orcid.org/0000-0001-5685-8004',
  'idx': 20,
  'gênero': 'Masculino',
  'nome orcid': 'Siome Goldenstein'},
 {'orcid': 'sem orcid',
  'idx': 21,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0003-4462-3325',
  'idx': 22,
  'gênero': 'Masculino',
  'nome orcid': 'Orlando Lee'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 23,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0001-5015-2131',
  'idx': 24,
  'gênero': 'Masculino',
  'nome orcid': 'Neucimar Leite'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 25,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'sem orcid',
  'idx': 26,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-8803-0401',
  'idx': 27,
  'gênero': 'Masculino',
  'nome orcid': 'Rodolfo Azevedo'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 28,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'orcid.org/0000-0001-5015-2131',
  'idx': 29,
  'gênero': 'Masculino',
  'nome orcid': 'Neucimar Leite'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 30,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0003-4869-5190',
  'idx': 31,
  'gênero': 'Masculino',
  'nome orcid': 'Guido Araujo'},
 {'orcid': 'orcid.org/0000-0002-8803-0401',
  'idx': 32,
  'gênero': 'Masculino',
  'nome orcid': 'Rodolfo Azevedo'},
 {'orcid': 'orcid.org/0000-0001-8309-6367',
  'idx': 33,
  'gênero': 'Feminino',
  'nome orcid': 'Ariadne Carvalho'},
 {'orcid': 'orcid.org/0000-0001-9174-2816',
  'idx': 34,
  'gênero': 'Masculino',
  'nome orcid': 'Joao C. Setubal'},
 {'orcid': 'orcid.org/0000-0001-7878-4990',
  'idx': 35,
  'gênero': 'Masculino',
  'nome orcid': 'Joao Meidanis'},
 {'orcid': 'orcid.org/0000-0001-5201-1244',
  'idx': 36,
  'gênero': 'Masculino',
  'nome orcid': 'Jacques Wainer'},
 {'orcid': 'orcid.org/0000-0002-3823-8941',
  'idx': 37,
  'gênero': 'Masculino',
  'nome orcid': 'Luiz Eduardo Buzato'},
 {'orcid': 'orcid.org/0000-0002-4830-5298',
  'idx': 38,
  'gênero': 'Feminino',
  'nome orcid': 'Maria Cecilia Calani Baranauskas'},
 {'orcid': 'sem orcid',
  'idx': 39,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-1067-6421',
  'idx': 40,
  'gênero': 'Masculino',
  'nome orcid': 'Flávio K. Miyazawa'},
 {'orcid': 'sem orcid',
  'idx': 0,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0003-4290-6508',
  'idx': 1,
  'gênero': 'Feminino',
  'nome orcid': 'Eliane Martins'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 2,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0003-2046-602X',
  'idx': 3,
  'gênero': 'Masculino',
  'nome orcid': 'Nelson L. S. da Fonseca'},
 {'orcid': 'orcid.org/0000-0002-8803-0401',
  'idx': 4,
  'gênero': 'Masculino',
  'nome orcid': 'Rodolfo Azevedo'},
 {'orcid': 'orcid.org/0000-0002-8803-0401',
  'idx': 5,
  'gênero': 'Masculino',
  'nome orcid': 'Rodolfo Azevedo'},
 {'orcid': 'orcid.org/0000-0003-4869-5190',
  'idx': 6,
  'gênero': 'Masculino',
  'nome orcid': 'Guido Araujo'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 7,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0001-9772-263X',
  'idx': 8,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Torres'},
 {'orcid': 'orcid.org/0000-0001-7878-4990',
  'idx': 9,
  'gênero': 'Masculino',
  'nome orcid': 'Joao Meidanis'},
 {'orcid': 'orcid.org/0000-0001-5015-2131',
  'idx': 10,
  'gênero': 'Masculino',
  'nome orcid': 'Neucimar Leite'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 11,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'orcid.org/0000-0002-4830-5298',
  'idx': 12,
  'gênero': 'Feminino',
  'nome orcid': 'Maria Cecilia Calani Baranauskas'},
 {'orcid': 'orcid.org/0000-0001-8309-6367',
  'idx': 13,
  'gênero': 'Feminino',
  'nome orcid': 'Ariadne Carvalho'},
 {'orcid': 'orcid.org/0000-0001-5201-1244',
  'idx': 14,
  'gênero': 'Masculino',
  'nome orcid': 'Jacques Wainer'},
 {'orcid': 'sem orcid',
  'idx': 15,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-9539-6874',
  'idx': 16,
  'gênero': 'Masculino',
  'nome orcid': 'Sandro Rigo'},
 {'orcid': 'sem orcid',
  'idx': 17,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-4830-5298',
  'idx': 18,
  'gênero': 'Feminino',
  'nome orcid': 'Maria Cecilia Calani Baranauskas'},
 {'orcid': 'orcid.org/0000-0001-5201-1244',
  'idx': 19,
  'gênero': 'Masculino',
  'nome orcid': 'Jacques Wainer'},
 {'orcid': 'orcid.org/0000-0001-5685-8004',
  'idx': 20,
  'gênero': 'Masculino',
  'nome orcid': 'Siome Goldenstein'},
 {'orcid': 'orcid.org/0000-0002-9539-6874',
  'idx': 21,
  'gênero': 'Masculino',
  'nome orcid': 'Sandro Rigo'},
 {'orcid': 'orcid.org/0000-0003-2046-602X',
  'idx': 22,
  'gênero': 'Masculino',
  'nome orcid': 'Nelson L. S. da Fonseca'},
 {'orcid': 'orcid.org/0000-0002-2914-5380',
  'idx': 23,
  'gênero': 'Masculino',
  'nome orcid': 'Alexandre Falcao'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 24,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0002-2914-5380',
  'idx': 25,
  'gênero': 'Masculino',
  'nome orcid': 'Alexandre Falcao'},
 {'orcid': 'sem orcid',
  'idx': 26,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-5945-0845',
  'idx': 27,
  'gênero': 'Masculino',
  'nome orcid': 'Cid de Souza'},
 {'orcid': 'sem orcid',
  'idx': 28,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 29,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0001-5201-1244',
  'idx': 30,
  'gênero': 'Masculino',
  'nome orcid': 'Jacques Wainer'},
 {'orcid': 'orcid.org/0000-0002-2914-5380',
  'idx': 31,
  'gênero': 'Masculino',
  'nome orcid': 'Alexandre Falcao'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 32,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0003-4869-5190',
  'idx': 33,
  'gênero': 'Masculino',
  'nome orcid': 'Guido Araujo'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 34,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 35,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'orcid.org/0000-0001-5015-2131',
  'idx': 0,
  'gênero': 'Masculino',
  'nome orcid': 'Neucimar Leite'},
 {'orcid': 'orcid.org/0000-0002-6540-8686',
  'idx': 1,
  'gênero': 'Masculino',
  'nome orcid': 'Paulo de Geus'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 2,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0001-9772-263X',
  'idx': 3,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Torres'},
 {'orcid': 'sem orcid',
  'idx': 4,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 5,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0001-9772-263X',
  'idx': 6,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Torres'},
 {'orcid': 'orcid.org/0000-0003-0683-7672',
  'idx': 7,
  'gênero': 'Feminino',
  'nome orcid': 'Anamaria Gomide'},
 {'orcid': 'orcid.org/0000-0002-2914-5380',
  'idx': 8,
  'gênero': 'Masculino',
  'nome orcid': 'Alexandre Falcao'},
 {'orcid': 'orcid.org/0000-0002-7002-875X',
  'idx': 9,
  'gênero': 'Masculino',
  'nome orcid': 'Ricardo Dahab'},
 {'orcid': 'orcid.org/0000-0001-5201-1244',
  'idx': 10,
  'gênero': 'Masculino',
  'nome orcid': 'Jacques Wainer'},
 {'orcid': 'orcid.org/0000-0002-4830-5298',
  'idx': 11,
  'gênero': 'Feminino',
  'nome orcid': 'Maria Cecilia Calani Baranauskas'},
 {'orcid': 'orcid.org/0000-0002-4830-5298',
  'idx': 12,
  'gênero': 'Feminino',
  'nome orcid': 'Maria Cecilia Calani Baranauskas'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 13,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'orcid.org/0000-0003-4290-6508',
  'idx': 14,
  'gênero': 'Feminino',
  'nome orcid': 'Eliane Martins'},
 {'orcid': 'orcid.org/0000-0001-5201-1244',
  'idx': 15,
  'gênero': 'Masculino',
  'nome orcid': 'Jacques Wainer'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 16,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 17,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 18,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'orcid.org/0000-0001-5685-8004',
  'idx': 19,
  'gênero': 'Masculino',
  'nome orcid': 'Siome Goldenstein'},
 {'orcid': 'orcid.org/0000-0002-1180-2637',
  'idx': 20,
  'gênero': 'Masculino',
  'nome orcid': 'Edmundo Madeira'},
 {'orcid': 'sem orcid',
  'idx': 21,
  'gênero': 'sem orcid',
  'nome orcid': 'sem orcid'},
 {'orcid': 'orcid.org/0000-0002-5945-0845',
  'idx': 22,
  'gênero': 'Masculino',
  'nome orcid': 'Cid de Souza'},
 {'orcid': 'orcid.org/0000-0003-1908-4753',
  'idx': 23,
  'gênero': 'Feminino',
  'nome orcid': 'Claudia Medeiros'},
 {'orcid': 'orcid.org/0000-0003-4549-7105',
  'idx': 24,
  'gênero': 'Feminino',
  'nome orcid': 'Cecilia Mary Fischer Rubira Rubira'},
 {'orcid': 'orcid.org/0000-0001-9772-263X',
  'idx': 25,

In [17]:
info

{'orcid': nan, 'idx': 15, 'gênero': 'não anotado', 'nome orcid': 'não anotado'}

In [22]:
for col, infos in generos.items():
    for info in infos:
        idx = info["idx"]
        genero = info["gênero"]
        orcid = info["orcid"]
        nome = info["nome orcid"]
        # if orcid == orcid and orcid.split("/")[-1] == "0000-0002-3823-8941":
        if nome == "Luiz Eduardo Buzato":
            print(nome, genero, idx)
        data_final.at[idx, f"{col}_genero"] = genero

Luiz Eduardo Buzato Masculino 11
Luiz Eduardo Buzato Masculino 49
Luiz Eduardo Buzato Masculino 28
Luiz Eduardo Buzato Masculino 51
Luiz Eduardo Buzato Masculino 6
Luiz Eduardo Buzato Masculino 12
Luiz Eduardo Buzato Masculino 26
Luiz Eduardo Buzato Masculino 30
Luiz Eduardo Buzato Masculino 20
Luiz Eduardo Buzato Masculino 30
Luiz Eduardo Buzato Masculino 2
Luiz Eduardo Buzato Masculino 28
Luiz Eduardo Buzato Masculino 48
Luiz Eduardo Buzato Masculino 65
Luiz Eduardo Buzato Masculino 66
Luiz Eduardo Buzato Masculino 40
Luiz Eduardo Buzato Masculino 38
Luiz Eduardo Buzato Masculino 44
Luiz Eduardo Buzato Masculino 42
Luiz Eduardo Buzato Masculino 36
Luiz Eduardo Buzato Masculino 30
Luiz Eduardo Buzato Masculino 55
Luiz Eduardo Buzato Masculino 37
Luiz Eduardo Buzato Masculino 53
Luiz Eduardo Buzato Masculino 4
Luiz Eduardo Buzato Masculino 26
Luiz Eduardo Buzato Masculino 43
Luiz Eduardo Buzato Masculino 1

In [16]:
data_final.head()

,tipo,url,orientador,avaliador1,avaliador2,avaliador3,avaliador4,avaliador5,avaliador6,orientador_filiação,...,avaliador3_keyword_11,avaliador3_keyword_12,avaliador3_keyword_13,avaliador1_genero,avaliador2_genero,avaliador3_genero,avaliador4_genero,avaliador5_genero,avaliador6_genero,orientador_genero
0,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-6540-8686,sem orcid,orcid.org/0000-0002-8803-0401,NaN,NaN,NaN,NaN,University of Campinas,...,NaN,NaN,NaN,sem orcid,Masculino,não anotado,não anotado,não anotado,não anotado,Masculino
1,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0002-6540-8686,sem orcid,orcid.org/0000-0002-7002-875X,NaN,NaN,NaN,NaN,University of Campinas,...,NaN,NaN,NaN,Masculino,Feminino,não anotado,não anotado,não anotado,não anotado,Feminino
2,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0003-4869-5190,orcid.org/0000-0002-8803-0401,orcid.org/0000-0003-1574-0362,NaN,NaN,NaN,NaN,Universidade Estadual de Campinas,...,NaN,NaN,NaN,sem orcid,Masculino,não anotado,não anotado,não anotado,não anotado,Masculino
3,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0001-5685-8004,sem orcid,orcid.org/0000-0002-7002-875X,NaN,NaN,NaN,NaN,no info,...,NaN,NaN,NaN,Masculino,Feminino,não anotado,não anotado,não anotado,não anotado,Masculino
4,MESTRADO,https://repositorio.unicamp.br/acervo/detalhe/...,orcid.org/0000-0001-5685-8004,orcid.org/0000-0001-5489-4909,orcid.org/0000-0002-9554-1381,orcid.org/0000-0002-3159-4839,NaN,NaN,NaN,no info,...,NaN,NaN,NaN,Masculino,Masculino,não anotado,não anotado,não anotado,não anotado,Masculino

In [32]:
data_final.iloc[101]["avaliador2_nome"], data_final.iloc[101]["avaliador2_genero"]

('Luiz Eduardo Buzato', 'Masculino')

In [33]:
data_final.iloc[101]

tipo                                             MESTRADO PROFISSIONAL
url                  https://repositorio.unicamp.br/acervo/detalhe/...
orientador                               orcid.org/0000-0002-1180-2637
avaliador1                                                   sem orcid
avaliador2                               orcid.org/0000-0002-3823-8941
                                           ...
avaliador3_genero                                            Masculino
avaliador4_genero                                          não anotado
avaliador5_genero                                          não anotado
avaliador6_genero                                          não anotado
orientador_genero                                            Masculino
Name: 30, Length: 98, dtype: object

## Salvando dataframe final

In [23]:
data_final.to_csv("final_defesas_2006a2024.csv", index=False)